import 'package:flutter/material.dart';
import 'models.dart';

const String adminEmail = 'admin@lumen.ng';
const int freeTrialDays = 7;

const Map<String, Map<String, dynamic>> subjects = {
  'Mathematics': {'icon': '∑', 'color': Color(0xFF2563EB)},
  'English': {'icon': 'Aa', 'color': Color(0xFF7C3AED)},
  'Physics': {'icon': '∮', 'color': Color(0xFF0891B2)},
  'Chemistry': {'icon': '⊕', 'color': Color(0xFF059669)},
  'Biology': {'icon': '◉', 'color': Color(0xFFD97706)},
};

const List<SubscriptionPlan> plans = [
  SubscriptionPlan(
    id: 'monthly',
    name: 'Monthly',
    price: 1500,
    days: 30,
    perks: ['Unlimited CBT Practice', 'All Study Groups', 'Flashcard Creator', 'AI Tutor', 'Leaderboard Access'],
  ),
  SubscriptionPlan(
    id: 'term',
    name: 'Per Term',
    price: 3500,
    days: 90,
    popular: true,
    perks: ['Everything in Monthly', '3-month access', 'Priority support', 'Early feature access', 'Battle mode'],
  ),
  SubscriptionPlan(
    id: 'yearly',
    name: 'Annual',
    price: 9999,
    days: 365,
    perks: ['Everything in Term', '1-year access', 'Admin badge', 'Exclusive resources', 'Study streak rewards'],
  ),
];

const Map<String, List<JambQuestion>> jambQuestions = {
  'Mathematics': [
    JambQuestion(q: 'If 2x+3=11, x=?', options: ['3', '4', '5', '6'], answer: 1, explain: '2x=8, x=4'),
    JambQuestion(q: '5²+3²=?', options: ['16', '25', '34', '64'], answer: 2, explain: '25+9=34'),
    JambQuestion(q: 'Simplify (2x³)(3x²)', options: ['5x⁵', '6x⁵', '5x⁶', '6x⁶'], answer: 1, explain: '6x⁵'),
    JambQuestion(q: '15% of 200?', options: ['15', '20', '30', '45'], answer: 2, explain: '0.15×200=30'),
    JambQuestion(q: 'Triangle 60°,60°: third angle?', options: ['30', '45', '60', '90'], answer: 2, explain: '180-120=60'),
    JambQuestion(q: 'Solve x²=49', options: ['x=7', 'x=±7', 'x=14', 'x=±14'], answer: 1, explain: '√49=±7'),
    JambQuestion(q: 'LCM of 4 and 6?', options: ['2', '12', '24', '10'], answer: 1, explain: 'LCM=12'),
    JambQuestion(q: '0.75 as fraction?', options: ['1/4', '1/2', '3/4', '7/5'], answer: 2, explain: '3/4'),
    JambQuestion(q: 'Area circle r=7 (π=22/7)?', options: ['154', '44', '49', '22'], answer: 0, explain: 'πr²=154'),
    JambQuestion(q: 'y=3x+2, x=4 → y=?', options: ['10', '12', '14', '16'], answer: 2, explain: '14'),
    JambQuestion(q: '√144=?', options: ['10', '11', '12', '14'], answer: 2, explain: '12'),
    JambQuestion(q: '3⁴=?', options: ['12', '27', '64', '81'], answer: 3, explain: '81'),
    JambQuestion(q: '5y=25 → y=?', options: ['3', '4', '5', '6'], answer: 2, explain: '5'),
    JambQuestion(q: 'Perimeter square side 6?', options: ['12', '18', '24', '36'], answer: 2, explain: '24'),
    JambQuestion(q: '20% of 150?', options: ['20', '25', '30', '35'], answer: 2, explain: '30'),
    JambQuestion(q: '3x-7=8 → x=?', options: ['3', '4', '5', '6'], answer: 2, explain: '5'),
    JambQuestion(q: 'HCF 12 and 18?', options: ['3', '6', '9', '12'], answer: 1, explain: '6'),
    JambQuestion(q: 'x/4=5 → x=?', options: ['9', '15', '20', '25'], answer: 2, explain: '20'),
    JambQuestion(q: 'LCM of 3 and 7?', options: ['10', '21', '14', '7'], answer: 1, explain: 'LCM=21'),
    JambQuestion(q: 'Mode of: 2,3,3,4,5?', options: ['2', '3', '4', '5'], answer: 1, explain: 'Most frequent=3'),
  ],
  'English': [
    JambQuestion(q: 'Correct spelling?', options: ['Accomodation', 'Accommodation', 'Acommodation', 'Accomadation'], answer: 1, explain: 'Double c, double m'),
    JambQuestion(q: '"Ephemeral" means?', options: ['Permanent', 'Short-lived', 'Eternal', 'Ancient'], answer: 1, explain: 'Very brief'),
    JambQuestion(q: 'Antonym of "benevolent"?', options: ['Kind', 'Generous', 'Malevolent', 'Charitable'], answer: 2, explain: 'Malevolent=wishing evil'),
    JambQuestion(q: 'Gerund in "Swimming is fun"?', options: ['Is', 'Fun', 'Swimming', 'None'], answer: 2, explain: 'Noun form of verb'),
    JambQuestion(q: '"Verbose" means?', options: ['Silent', 'Brief', 'Wordy', 'Angry'], answer: 2, explain: 'Using excess words'),
    JambQuestion(q: '"Bibliophile" loves?', options: ['Music', 'Books', 'Art', 'Nature'], answer: 1, explain: 'Biblio=book'),
    JambQuestion(q: 'Which is a conjunction?', options: ['Quickly', 'And', 'Beautiful', 'Run'], answer: 1, explain: 'Joins clauses'),
    JambQuestion(q: '"Loquacious" means?', options: ['Quiet', 'Talkative', 'Angry', 'Lazy'], answer: 1, explain: 'Very talkative'),
    JambQuestion(q: 'Plural of "criterion"?', options: ['Criterions', 'Criterias', 'Criteria', 'Criterian'], answer: 2, explain: 'Greek: criteria'),
    JambQuestion(q: '"Ameliorate" means?', options: ['Worsen', 'Improve', 'Ignore', 'Delay'], answer: 1, explain: 'Make better'),
    JambQuestion(q: '"Ubiquitous" means?', options: ['Rare', 'Unique', 'Everywhere', 'Ancient'], answer: 2, explain: 'Present everywhere'),
    JambQuestion(q: 'Plural of "phenomenon"?', options: ['Phenomenons', 'Phenomena', 'Phenomenas', 'Phenomenon'], answer: 1, explain: 'Greek origin'),
    JambQuestion(q: 'Antonym of "diligent"?', options: ['Hardworking', 'Careful', 'Lazy', 'Smart'], answer: 2, explain: 'Lazy'),
    JambQuestion(q: 'Plural of "analysis"?', options: ['Analysises', 'Analyses', 'Analysis', 'Analysiss'], answer: 1, explain: 'Greek: analyses'),
    JambQuestion(q: 'Subject-verb: "Each of the students ___ present"', options: ['are', 'were', 'is', 'be'], answer: 2, explain: 'Each=singular'),
    JambQuestion(q: 'Synonym of "gregarious"?', options: ['Shy', 'Sociable', 'Aggressive', 'Studious'], answer: 1, explain: 'Fond of company'),
    JambQuestion(q: 'Which is adjective?', options: ['Quickly', 'Happiness', 'Brilliant', 'Run'], answer: 2, explain: 'Describes nouns'),
    JambQuestion(q: '"Obstinate" means?', options: ['Flexible', 'Stubborn', 'Kind', 'Weak'], answer: 1, explain: 'Very stubborn'),
    JambQuestion(q: 'Which is a simile?', options: ['Moon is a lamp', 'She runs like wind', 'Time flies', 'Road snaked'], answer: 1, explain: 'Uses like/as'),
    JambQuestion(q: '"Taciturn" means?', options: ['Loud', 'Reserved/quiet', 'Angry', 'Happy'], answer: 1, explain: 'Habitually silent'),
  ],
  'Physics': [
    JambQuestion(q: 'Unit of force?', options: ['Watt', 'Joule', 'Newton', 'Pascal'], answer: 2, explain: 'N=kg·m/s²'),
    JambQuestion(q: 'Speed of light?', options: ['3×10⁶', '3×10⁸', '3×10¹⁰', '3×10⁴'], answer: 1, explain: '3×10⁸ m/s'),
    JambQuestion(q: 'Newton 2nd law: F=?', options: ['mv', 'ma', 'mv²', 'mg'], answer: 1, explain: 'F=ma'),
    JambQuestion(q: 'Scalar quantity?', options: ['Velocity', 'Force', 'Speed', 'Displacement'], answer: 2, explain: 'Speed: magnitude only'),
    JambQuestion(q: 'Unit of power?', options: ['Joule', 'Newton', 'Watt', 'Pascal'], answer: 2, explain: 'W=J/s'),
    JambQuestion(q: 'Ohm\'s law: V=?', options: ['I/R', 'IR', 'I+R', 'I-R'], answer: 1, explain: 'V=IR'),
    JambQuestion(q: 'g on Earth?', options: ['8.9', '9.8', '10.8', '11'], answer: 1, explain: '9.8 m/s²'),
    JambQuestion(q: 'NOT electromagnetic?', options: ['X-rays', 'Sound waves', 'Gamma rays', 'Radio waves'], answer: 1, explain: 'Sound needs medium'),
    JambQuestion(q: 'Unit of charge?', options: ['Ampere', 'Volt', 'Coulomb', 'Ohm'], answer: 2, explain: 'Coulomb(C)'),
    JambQuestion(q: 'Work = Force × ?', options: ['Time', 'Mass', 'Distance', 'Velocity'], answer: 2, explain: 'W=Fd'),
    JambQuestion(q: 'Unit of frequency?', options: ['Second', 'Hertz', 'Metre', 'Watt'], answer: 1, explain: 'Hz=cycles/s'),
    JambQuestion(q: 'Mirror in headlights?', options: ['Plane', 'Convex', 'Concave', 'None'], answer: 2, explain: 'Concave converges light'),
    JambQuestion(q: 'Energy in capacitor?', options: ['CV', '½CV²', 'C/V', 'CV²'], answer: 1, explain: 'E=½CV²'),
    JambQuestion(q: 'λ×f=?', options: ['Amplitude', 'Speed', 'Period', 'Energy'], answer: 1, explain: 'v=fλ'),
    JambQuestion(q: 'Highest frequency in EM?', options: ['Radio', 'X-ray', 'Visible', 'Gamma'], answer: 3, explain: 'Gamma rays'),
    JambQuestion(q: 'Converts electrical to mechanical?', options: ['Generator', 'Resistor', 'Motor', 'Capacitor'], answer: 2, explain: 'Electric motor'),
    JambQuestion(q: 'TIR when angle?', options: ['Less than critical', 'Equal critical', 'Greater critical', 'Zero'], answer: 2, explain: 'Greater than critical angle'),
    JambQuestion(q: 'Lens formula 1/f=?', options: ['1/u+1/v', '1/u-1/v', 'u+v', 'u×v'], answer: 0, explain: '1/v+1/u'),
    JambQuestion(q: 'Specific heat unit?', options: ['J/kg', 'J/kg·K', 'W/m·K', 'J/K'], answer: 1, explain: 'J/(kg·K)'),
    JambQuestion(q: 'Transformer principle?', options: ['Self induction', 'Mutual induction', 'Electrostatics', 'Thermoelectricity'], answer: 1, explain: 'Mutual EM induction'),
  ],
  'Chemistry': [
    JambQuestion(q: 'Atomic number of Carbon?', options: ['4', '6', '8', '12'], answer: 1, explain: '6 protons'),
    JambQuestion(q: 'Formula of water?', options: ['H₂O₂', 'HO', 'H₂O', 'H₃O'], answer: 2, explain: 'H₂O'),
    JambQuestion(q: 'Noble gas?', options: ['Nitrogen', 'Oxygen', 'Argon', 'Chlorine'], answer: 2, explain: 'Group 18'),
    JambQuestion(q: 'Neutral pH?', options: ['0', '7', '14', '1'], answer: 1, explain: 'pH 7'),
    JambQuestion(q: 'Symbol for Gold?', options: ['Go', 'Gd', 'Au', 'Ag'], answer: 2, explain: 'Au=Aurum'),
    JambQuestion(q: 'Avogadro\'s number?', options: ['6.02×10²¹', '6.02×10²³', '6.02×10²⁵', '6.02×10²²'], answer: 1, explain: '6.022×10²³'),
    JambQuestion(q: 'Acid pH?', options: ['>7', '=7', '<7', 'Any'], answer: 2, explain: 'pH<7'),
    JambQuestion(q: 'Which is mixture?', options: ['Water', 'Salt', 'Air', 'Diamond'], answer: 2, explain: 'Air=N₂+O₂+...'),
    JambQuestion(q: 'Valency of Oxygen?', options: ['1', '2', '3', '4'], answer: 1, explain: '2 bonds'),
    JambQuestion(q: 'NaCl bond type?', options: ['Covalent', 'Metallic', 'Ionic', 'Hydrogen'], answer: 2, explain: 'Na⁺Cl⁻'),
    JambQuestion(q: 'Formula sulfuric acid?', options: ['HCl', 'H₂SO₃', 'H₂SO₄', 'HSO₄'], answer: 2, explain: 'H₂SO₄'),
    JambQuestion(q: 'Isotopes have same?', options: ['Mass number', 'Neutrons', 'Protons', 'All'], answer: 2, explain: 'Same Z (protons)'),
    JambQuestion(q: 'Lightest element?', options: ['Helium', 'Oxygen', 'Hydrogen', 'Carbon'], answer: 2, explain: 'H, Z=1'),
    JambQuestion(q: 'Electrolysis of water?', options: ['H₂ only', 'O₂ only', 'H₂ and O₂', 'CO₂'], answer: 2, explain: 'Cathode H₂, Anode O₂'),
    JambQuestion(q: 'NOT hydrocarbon?', options: ['Methane', 'Ethanol', 'Propane', 'Butane'], answer: 1, explain: 'Ethanol has O'),
    JambQuestion(q: 'Most electronegative?', options: ['Oxygen', 'Chlorine', 'Nitrogen', 'Fluorine'], answer: 3, explain: 'F highest'),
    JambQuestion(q: 'Atomic mass Na?', options: ['11', '23', '12', '22'], answer: 1, explain: '23 amu'),
    JambQuestion(q: 'Rusting is?', options: ['Physical', 'Chemical', 'Nuclear', 'None'], answer: 1, explain: 'Fe₂O₃ forms'),
    JambQuestion(q: 'Catalyst?', options: ['Consumed', 'Raises Ea', 'Speeds up, not consumed', 'Changes equilibrium'], answer: 2, explain: 'Lowers activation energy'),
    JambQuestion(q: 'Conservation of mass?', options: ['Mass created', 'Mass destroyed', 'Mass conserved', 'Mass=energy'], answer: 2, explain: 'Reactants=Products mass'),
  ],
  'Biology': [
    JambQuestion(q: 'Basic unit of life?', options: ['Tissue', 'Organ', 'Cell', 'Nucleus'], answer: 2, explain: 'All life=cells'),
    JambQuestion(q: 'Photosynthesis in?', options: ['Mitochondria', 'Ribosome', 'Chloroplast', 'Nucleus'], answer: 2, explain: 'Chloroplasts'),
    JambQuestion(q: 'Fight infection?', options: ['RBC', 'WBC', 'Platelets', 'Plasma'], answer: 1, explain: 'Leukocytes'),
    JambQuestion(q: 'DNA found in?', options: ['Cytoplasm', 'Ribosome', 'Nucleus', 'Membrane'], answer: 2, explain: 'Nucleus'),
    JambQuestion(q: 'Osmosis: water moves?', options: ['High→low conc', 'Dilute→concentrated', 'High solute→low', 'None'], answer: 1, explain: 'Dilute to concentrated'),
    JambQuestion(q: 'Prokaryote?', options: ['Amoeba', 'Bacteria', 'Fungi', 'Plant'], answer: 1, explain: 'No nucleus membrane'),
    JambQuestion(q: 'Powerhouse of cell?', options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Vacuole'], answer: 2, explain: 'ATP production'),
    JambQuestion(q: 'Human chromosomes?', options: ['23', '44', '46', '48'], answer: 2, explain: '46=23 pairs'),
    JambQuestion(q: 'Vitamin from sunlight?', options: ['A', 'B', 'C', 'D'], answer: 3, explain: 'UV→Vitamin D'),
    JambQuestion(q: 'Transpiration is?', options: ['Water absorption', 'Water loss via leaves', 'Photosynthesis', 'Respiration'], answer: 1, explain: 'Via stomata'),
    JambQuestion(q: 'Enzymes are?', options: ['Carbohydrates', 'Lipids', 'Proteins', 'Nucleic acids'], answer: 2, explain: 'Biological protein catalysts'),
    JambQuestion(q: 'Blood type no antigens?', options: ['A', 'B', 'AB', 'O'], answer: 3, explain: 'Type O'),
    JambQuestion(q: 'Fertilization occurs?', options: ['Uterus', 'Ovary', 'Fallopian tube', 'Cervix'], answer: 2, explain: 'Fallopian tube'),
    JambQuestion(q: 'Study of heredity?', options: ['Ecology', 'Genetics', 'Physiology', 'Taxonomy'], answer: 1, explain: 'Genetics'),
    JambQuestion(q: 'Cellulose is?', options: ['Protein', 'Lipid', 'Carbohydrate', 'Nucleic acid'], answer: 2, explain: 'Polysaccharide'),
    JambQuestion(q: 'Insulin produced by?', options: ['Liver', 'Kidney', 'Pancreas', 'Thyroid'], answer: 2, explain: 'Beta cells, pancreas'),
    JambQuestion(q: 'Malaria caused by?', options: ['Virus', 'Bacteria', 'Protozoan', 'Fungus'], answer: 2, explain: 'Plasmodium'),
    JambQuestion(q: 'Mitosis results in?', options: ['4 haploid', '2 haploid', '2 diploid', '4 diploid'], answer: 2, explain: '2 identical diploid'),
    JambQuestion(q: 'Stomata function?', options: ['Absorption', 'Gas exchange', 'Support', 'Storage'], answer: 1, explain: 'CO₂ in, O₂/H₂O out'),
    JambQuestion(q: 'NOT liver function?', options: ['Bile production', 'Detoxification', 'Insulin secretion', 'Glycogen storage'], answer: 2, explain: 'Pancreas makes insulin'),
  ],
};
